name: JSConf US Last Call
register_sponsors: https://docs.google.com/forms/d/1LYMqncz3INKhal0cPYu-SCVISeifEHYrvfah5paBjBc/viewform
description: "JSConf, One Last Time."
shortname: JSConf
url: http://lastcall.jsconf.us
tickets: https://ti.to/jsconf-us/last-call
cfp: https://docs.google.com/a/jsconf.com/forms/d/1tN_QWHAUA55_qD53tDw28jgNiyss6k_3Bc9ekaoMwbY/viewform
exclude:
  - README.md
  - CONTRIBUTING.md
markdown: redcarpet
highlighter: pygments
